# Generated by Django 3.1.1 on 2021-05-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('firstname', models.CharField(max_length=145)),
                ('lastname', models.CharField(max_length=145)),
                ('position', models.CharField(max_length=245)),
                ('area', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.PositiveSmallIntegerField(default=0)),
                ('is_superuser', models.PositiveSmallIntegerField(default=0)),
                ('is_staff', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
