# Generated by Django 3.1.1 on 2021-06-02 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_signatory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signatory',
        ),
    ]
