# Generated by Django 3.1.1 on 2021-04-27 02:19

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='meters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateforwarded', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('rrnumber', models.CharField(db_index=True, max_length=145)),
                ('brand', models.CharField(max_length=145)),
                ('metertype', models.CharField(max_length=145, null=True)),
                ('serialnos', models.CharField(max_length=145, null=True)),
                ('units', models.IntegerField(default=0)),
                ('active', models.PositiveSmallIntegerField(default=0)),
                ('userid', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meters',
            },
        ),
        migrations.CreateModel(
            name='meterserials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idmeters', models.IntegerField(db_index=True, default=0)),
                ('serialno', models.CharField(max_length=45)),
                ('ampheres', models.CharField(max_length=45, null=True)),
                ('accuracy', models.CharField(max_length=45, null=True)),
                ('wms_status', models.PositiveSmallIntegerField(default=0, null=True)),
                ('status', models.PositiveSmallIntegerField(default=0, null=True)),
                ('active', models.PositiveSmallIntegerField(default=0, null=True)),
                ('userid', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meter_serials',
            },
        ),
        migrations.CreateModel(
            name='meterserials_details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idmeterserials', models.IntegerField(db_index=True, default=0)),
                ('testdate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('gen_average', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fullload_average', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fl1', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fl2', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fl3', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('lightload_average', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ll1', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ll2', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ll3', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reading', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('type', models.PositiveSmallIntegerField(default=0, null=True)),
                ('volts', models.CharField(max_length=45)),
                ('phase', models.CharField(max_length=45)),
                ('kh', models.CharField(max_length=45)),
                ('ta', models.CharField(max_length=45)),
                ('remarks', models.CharField(max_length=245)),
                ('active', models.PositiveSmallIntegerField(default=0, null=True)),
                ('isdamage', models.BooleanField(default=False)),
                ('userid', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'meter_serials_details',
            },
        ),
    ]
