# Generated by Django 3.1.1 on 2021-04-27 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterserials',
            name='idmeters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meters.meters'),
        ),
    ]
