# Generated by Django 3.1.1 on 2021-05-28 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0003_auto_20210427_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterserials',
            name='idmeters',
            field=models.ForeignKey(db_column='idmeters', on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='Meters.meters'),
        ),
    ]
