# Generated by Django 3.1.1 on 2021-06-07 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0006_auto_20210604_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterserials_details',
            name='idmeterserials',
            field=models.ForeignKey(db_column='idmeterserials', on_delete=django.db.models.deletion.CASCADE, related_name='meterserials', to='Meters.meters'),
        ),
    ]
