# Generated by Django 3.1.1 on 2021-06-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signatory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calibratedby', models.CharField(max_length=45)),
                ('calibratedby_position', models.CharField(max_length=45)),
                ('checkedby', models.CharField(max_length=45)),
                ('checkedby_position', models.CharField(max_length=45)),
                ('notedby', models.CharField(max_length=45)),
                ('notedby_position', models.CharField(max_length=45)),
                ('preparedby', models.CharField(max_length=45)),
                ('preparedby_position', models.CharField(max_length=45)),
                ('receivedby', models.CharField(max_length=45)),
                ('receivedby_position', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'signatory',
            },
        ),
    ]
